### ISSUE TITLE
Playwright-perl interfering with DBI.pm

### ISSUE THREAD

**Issue by tod222** [teodesian/playwright-perl#32]
Somehow Playwright-perl is interfering with DBI by destroying/closing connections to the database server.

This [test script](https://gist.github.com/tod222/cb20a4b4debd0990b3e1ace36a1d4448#file-pwp_dbi_issue_download) and [its output](https://gist.github.com/tod222/cb20a4b4debd0990b3e1ace36a1d4448#file-output_from_pwp_dbi_issue_download) reproduce the issue.

**Comment by teodesian** [comment]
So the first two checks worked, but the last failed.  Nothing jumping out at me immediately as to the cause.

Questions:

is the DB server running on the same source as the page queried, or on the same host as the playwright script?
Presumably they are on different ports at least, or we would not be getting any response.

Does the script work when the DB actions are not done?

**Comment by tod222** [comment]
The DB server, the host running the test script/Playwright, and the page(s) are all different machines. This has happened with two different sites.

Yes, the script "works" if the checkdb subroutine is short-circuited with a return, but this issue isn't breakage in Playwright-perl. It's that Playwright-perl is running fine but causes breakage in DBI.pm.

I should note that the two cases/sites I've tried so far both involved downloading, and that I can't reproduce the issue without initiating a download (although I've not spent a lot of time on this yet).

**Comment by tod222** [comment]
I added another checkdb call to isolated it to this line, which triggers the download:
`$page->select('//td[.="150 kB"]/..//a[.="Download sample pdf file"]')->click();`

**Comment by teodesian** [comment]
Cool, and unexpected.  Just for clarification, what kind of DB is it?  It might be specific to DBD::mysql or postgres or sqlite.

**Comment by tod222** [comment]
PostgreSQL 10.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18) 6.3.0 20170516, 64-bit

**Comment by teodesian** [comment]
Thanks, will take a look tomorrow!

**Comment by teodesian** [comment]
It doesn't seem to be DBI causing the issue for me, but I did get the download event time out, and it's not an obvious race or anything.

The unexpected disco for you is probably not DBI related -- it may be the playwright server crashing...or we raced the shutdown routine?

What version of playwright is installed? curious if that explains the different behavior

**Comment by teodesian** [comment]
Looks like firefox is loading the PDF directly and never firing a download event.
It's loaded in it's documentViewer which feels pretty 'here be dragons' RE automating it.
Perhaps there's a way to instruct the browser to not do this and force download instead.

**Comment by teodesian** [comment]
Guessing we need to tell the firefox profile to do pdfjs.disabled=1
https://stackoverflow.com/questions/23800195/auto-download-pdf-in-firefox

**Comment by teodesian** [comment]
looks like the firefoxUserPrefs field during launch, let's see

**Comment by tod222** [comment]
I don't think pdfjs.disabled works anymore.

To get direct downloads with no dialog you need to modify handlers.json:
```
                "application/pdf": {
                        "extensions": ["pdf"],
                        "action": 0
                },

```

**Comment by teodesian** [comment]
Hmm, seems to work when I change directly in about.config, but not via firefoxUserPrefs during launch.

Maybe I'm not passing this right with the server?

**Comment by tod222** [comment]
I was hoping Playwright would provide a **perform dialog-free downloads for every mime type** option, but no. These APIs myopically focused on testing omit functionality useful to non-testing use cases for automation.

**Comment by tod222** [comment]
On S::R::D user prefs hasn't worked to suppress download dialogs with Firefox in forever. The only thing that seems to work are supplying a profile with mime type entries in handlers.json.

**Comment by teodesian** [comment]
> These APIs myopically focused on testing omit functionality needed for non-testing use cases for automation.

Sometimes dogmatically so, unfortunately.  The "anti-scrape" mentality is present in Playwright as far as I can tell as well.  Really ridiculous when you get down to it, many successful businesses are built around doing precisely this; plaid in particular.

Thanks for the advice -- I'll poke around with it until I get something that works, and build it in as a constructor option for convenience.

**Comment by teodesian** [comment]
Got it to work!  Just had to coerce the bool properly:
`my $browser = $handle->launch( headless => 0, type => 'firefox', firefoxUserPrefs => { 'pdfjs.disabled' => JSON::true } );`
I'll make sure the auto-coerce descends into userPrefs too.

**Comment by teodesian** [comment]
now I think I see what you are seeing:
`DBD::Pg::st execute failed: SSL connection has been closed unexpectedly at test.pl line 15.`
guessing the destructor is resulting in an unclean shutdown of the pg conn?

**Comment by teodesian** [comment]
Working theory:

https://rt.cpan.org/Public/Bug/Display.html?id=65738

In short, I probably have a good reason to implement #18

**Comment by teodesian** [comment]
Bad theory.  Implemented #18, but issue persists.  fascinating

**Comment by teodesian** [comment]
Ok, so I suspect this is a scoping issue, removing the code which awaits ( a fork happens!) fixes the problem.

This means that when the fork terminates the destructor fires for the database handle.  Which means I need to disable destructors in the fork somehow, or other callers will trip up too.

**Comment by teodesian** [comment]
yup, a quick POSIX::_exit() in the fork and we're right as rain

**Comment by tod222** [comment]
Beautiful! Thanks a lot for such a quick fix!

**Comment by teodesian** [comment]
Happy to help.  If you or anyone you know needs a hand with this sort of thing, let me know.  I'm always on the hunt for new clients.
