### ISSUE TITLE
Can't locate object method "select" via package "Playwright::ElementHandle"

### ISSUE THREAD

**Issue by tod222** [teodesian/playwright-perl#34]
Oops, this error shouldn't happen.

Here's a little [test script](https://gist.github.com/tod222/7ff57b213e8a28d6bcaf69754c6f2c45#file-pwp_issue_34) to reproduce the error.

**Comment by teodesian** [comment]
hmm, here's hoping the map of $ and $$ from playwright didn't get mucked up somehow. I'll look tomorrow morning.

**Comment by teodesian** [comment]
quick ask -- playwright version (from npm) installed?

**Comment by tod222** [comment]
```
$ npx playwright -V
Version 1.12.3
$ cpan-outdated | grep Playwright
T/TE/TEODESIAN/Playwright-0.009.tar.gz
```

**Comment by teodesian** [comment]
can reproduce.  I then notice this case is not in my example which I use to test.  of course this is where the bugs lie.  This usage is also in my synopsis, making it clear this should? be supported.  I'll have to check the spec if this is supported upstream (I *think* this is why I put it in synopsis), but if not I can probably shove it in there now that the parent page is an attribute of the element.

**Comment by tod222** [comment]
Yes, it's supported upstream: [elementHandle.$(selector)](https://playwright.dev/docs/api/class-elementhandle#element-handle-query-selector).

The parent page handle isn't needed for this (it's needed to run js code from an element handle).

**Comment by teodesian** [comment]
curiously, the api spec as generated by playwright's own generateApiJson.js renders this as querySelector and querySelectorAll now, which is divergent from their official documentation.

This explains the failure.  I'll have to map those names as well.

**Comment by teodesian** [comment]
Yep, that fixed it.

The only other thing to mention is that it choked on your example selector because it was not prepended with xpath=, as suggested in the selector documentation for playwright.

**Comment by tod222** [comment]
> it was not prepended with xpath=

I left that out by mistake.

> Yep, that fixed it.

Nice!

**Comment by teodesian** [comment]
I've sent it up to CPAN, it should get indexed before tonight.  Thanks as always for the reports.
