### ISSUE TITLE
Playwright.pm error from JSON/backportPP.pm

### ISSUE THREAD

**Issue by tod222** [teodesian/playwright-perl#37]
[pwp_issue_37](https://gist.github.com/tod222/c57d1fa5a9b6a81a9ebf4cde86a46d6c) dies with the following error:

> encountered object 'Playwright::ElementHandle=HASH(0x56088048dbd0)', but neither allow_blessed, convert_blessed nor allow_tags settings are enabled (or TO_JSON/FREEZE method missing) at /home/tod/perl5/lib/perl5/Playwright/Util.pm line 25.

**Comment by teodesian** [comment]
Ahh.  I'll need to unbless element handles passed in for convenience.
This is not strictly supported yet but makes sense.
I'll make the necessary adjustments tomorrow.

**Comment by teodesian** [comment]
Sent up to CPAN as 0.012
