### ISSUE TITLE
Moo.pm breaks Playwright.pm

### ISSUE THREAD

**Issue by tod222** [teodesian/playwright-perl#38]
[pwp_issue_38](https://gist.github.com/tod222/a6a2728000e35e5b5dda5f34b4349a57#file-pwp_issue_38) dies with

`Can't call method "evaluate" on an undefined value at src/issues/pwp_issue_38 line 18.`

Removing the `use Moo;` line allows the script to run to completion.

This may be less of a bug than a result of the implementation, but S::R::D was written using Moo which made it very easy to extend. Playwright.pm can be extended in a limited way by adding new methods, but without the ability to modify methods using features such as Moo's **before**, **after**, and **around**, Playwright.pm's extensibility is diminished in comparison to S::R::D.

**Comment by teodesian** [comment]
Consider doing your moo-ification after new() that's when the Sub::Install magic happens.

**Comment by teodesian** [comment]
nope, that doesn't work because all that is run in BEGIN.  I'll have to see if there's a runtime moo-ification technique.

**Comment by teodesian** [comment]
Looks like the easiest solution is to just wrap Playwright::Base with the mop

**Comment by teodesian** [comment]
yeah, there's no real way around that without just going all in on a mop.
We've got an equivalent to the after() sub with the callback functionality, but it's global to all the child objects.

The design of this was for ease of maintenance -- I didn't want to have to make huge adjustments when upstream changes the spec, which they do frequently.  This is in contrast to S::R::D which has a method for every selenium call there is, and has become more polyfills than client code.

It'll take a bit to research whether I can moo-ify something at runtime, or whether I can get all the sub::install stuff back in the BEGIN block (where it used to be).  The latter presents pretty severe tradeoffs given we actually query the playwright server itself to get the list of subroutines to build.  I'd essentially have to copy a perl version of the spec into the modules which sort of kills the idea of ease of maintenance.  Perhaps briefly running the server in BEGIN to get the spec spat out is the answer.

**Comment by tod222** [comment]
> Perhaps briefly running the server in BEGIN to get the spec spat out is the answer.

That's sounds like the route I'd take.

**Comment by teodesian** [comment]
Yep.  I'll give that a go tomorrow

**Comment by teodesian** [comment]
Been doing research on the best way to do this as a sort of static code generation.  Will get back to it soon, as I think I have a solution now.

**Comment by tod222** [comment]
Cool, sounds good!

**Comment by teodesian** [comment]
Have got a local branch with most of the stub classes built statically, and should be able to get them fleshed out soon.

Made minor mods to your test script:
```
#!/usr/bin/perl

use strict;
use warnings;
use Playwright;

{
    package Playwright::ElementHandle;
    use Moo;
    around 'evaluate' => sub { print "MOOOOOO\n" };
}

my $handle = Playwright->new( debug => 1 );
my $browser = $handle->launch( headless => 0, type => 'firefox' );
my $page = $browser->newPage({ acceptDownloads => 1 }); 

$page->goto('https://metacpan.org/pod/Playwright#Scripts', { waitUntil => 'networkidle' }); 
my $h2 = $page->select('//h2[@id="Scripts"]');
$h2->evaluate('arguments[0].style.backgroundColor = "#FF0000"; return 1;');
```
You shouldn't have to refer to the parent to evaluate() on elementhandles when done here.

**Comment by tod222** [comment]
Calling evaluate directly from an ElementHandle will be nice. Less typing FTW!

I'm looking forward to the release.

**Comment by teodesian** [comment]
Me too!  Been super busy, but may get a chance to finish it up tomorrow.

**Comment by teodesian** [comment]
Sent up to CPAN
