### ISSUE TITLE
Hide spec to improve signal-to-noise ratio of Data::Dumper?

### ISSUE THREAD

**Issue by tod222** [teodesian/playwright-perl#45]
About this:
```
use Data::Dumper;
print Dumper($instance->{spec});
```
While this is handy for looking at the spec, when trying to examine _other_ parts of a Playwright.pm object or a structure that happens to _contain_ a Playwright.pm object, the output is dominated by the contents of the spec. This is unhelpful.

Why not export a package global that contains the reference to the spec? Then the spec could still be examined easily and it would stay out of the way when using Data::Dumper to look at other things.

**Comment by teodesian** [comment]
There's not a else in there.  That said, if you are making subclasses I can see the utility.

I can modify things to have a ->spec() method which just refers to the right place in the global spec.

**Comment by tod222** [comment]
This would be great so that dumping tiny little structures doesn't get buried in the avalanche of ~30000 lines of specs.
