### ISSUE TITLE
Connecting to an existing playwright_server

### ISSUE THREAD

**Issue by garnier-quentin** [teodesian/playwright-perl#49]
Hi,

First, thanks for your work.

It will be nice to use an existing playwright_server. I executed the server:
```
$ node /usr/local/bin/playwright_server --debug
Listening on port 6969
```

I have looked the code and the perl module forks and execute its own playwright_server. We could get a better memory consumption if we use the same playwright_server for X clients.

**Comment by teodesian** [comment]
I should allow the port to be passed to allow this at the bare minimum.  Ideally an IP as well.

I'll look at implementing this soon.

**Comment by teodesian** [comment]
ok, so if you pass 'port' to the constructor it'll honor the option going forward.  Be sure to clean up with `bin/reap_playwright_servers` when all scripts are done testing.

**Comment by garnier-quentin** [comment]
Thanks for the PR. I have patched the version 0.17. It's working but i have following messages:
```
Odd number of elements in anonymous hash at /usr/local/share/perl/5.32.1/Playwright.pm line 111.
Use of uninitialized value in numeric eq (==) at /usr/local/share/perl/5.32.1/Playwright.pm line 215
```

Line 111:
```
            pid     => _start_server(
                $port, $timeout, $options{debug}, $options{cleanup} // 1
            ),
```

Line 215:
```
return unless $$ == $self->{parent} // 'bogus';
```

**Comment by teodesian** [comment]
$$ must be undef in this situation too, wonderful.

 

I’ll put in another patch.

 

GSB

**Comment by teodesian** [comment]
sent up to CPAN

**Comment by garnier-quentin** [comment]
Thanks! It's fixed the warnings.
