### ISSUE TITLE
Element locators are not working

### ISSUE THREAD

**Issue by whity** [teodesian/playwright-perl#54]
Hello,

When trying to call any `locator` method, e.g. `getByRole` or even `locator`, always get the following error `Exception found: Can't call method "[action]" on unblessed reference`.

from what could see, the mapper in `Playwright::Base::_api_request` isn't working because the response is different

```
          {
            '_selector' => 'internal:role=button[name="submit"i]',
            '_frame' => {
                          '_type' => 'Frame',
                          '_guid' => 'frame@6f8806f4d3b637319e334104d33c8dc3'
                        }
          }

```

playwright locators doc https://playwright.dev/docs/locators

**Comment by teodesian** [comment]
Apologies for the delay on this one.

Looks like the spec is not translating into the mapper correctly $Playwright::mapper.

Working on a fix.

**Comment by teodesian** [comment]
So what is going on is that these new locator methods, like most things which have been newly added, are missing the _type and _guid attributes internally in playwright.

I'll have to handle this.

**Comment by teodesian** [comment]
Looks like they're internally implemented as protocol buffers, and have a very different API to the rest of the Playwright internals.

I'll have to adjust playwright_server to fix this.

**Comment by teodesian** [comment]
The above patch should add the ability to call locator() on Page objects.

Let me know if any of the individual Locator class methods fail by filing new issues.

Thank you for the submission.

**Comment by whity** [comment]
great, thanks, i'll try this out when i find sometime, hopefully soon :)
