### ISSUE TITLE
method locator "getByLabel" not working

### ISSUE THREAD

**Issue by whity** [teodesian/playwright-perl#56]
Hello,

The method locator `getByLabel` still does not work

```perl
$page->getBylabel('my "label');
```
returns

```perl
          {
            '_selector' => 'internal:label="my \\"label"i',
            '_frame' => {
                          '_type' => 'Frame',
                          '_guid' => 'frame@9f71c8e230fd7e5b6bce37ad7f2c21ae'
                        }
          }

```

did not test the others, `getByAltText|getByTitle|getByPlaceholder|getByText|getByRole` but, i think they have same problem :)

thanks.

**Comment by teodesian** [comment]
Makes sense.  I suspect I'll need to add handlers for all the methods on Page which return Locator objects for the same reason.

**Comment by teodesian** [comment]
Needs to happen on Frame objects as well, and return FrameLocator instead of locator in that case too.

**Comment by teodesian** [comment]
Found a way to get them blessed correctly for everything returning Locator objects, so hopefully this handles all the new locator methods they add in the future too.  Will go up to CPAN shortly.
