### ISSUE TITLE
$result->text() stopped working

### ISSUE THREAD

**Issue by noppel** [teodesian/playwright-perl#59]
Some code that was working

    my $async = $page->waitForEvent('console');
    $page->evaluate('console.log(navigator.userAgent)');
    my $result = $handle->await( $async );
    my $logged = $result->text();

Is no longer working (Can't call method "text" on unblessed reference).

**Comment by teodesian** [comment]
Apologies for the delay in response.

The data structure underlying has changed unexpectedly, and was not advertised by playwright's specification JSON.  As such the response failed to be objectified correctly.

I'll have to put in a hack to make this work.
