### ISSUE TITLE
reap_playwright_servers - too few arguments to Playwright::Util::request

### ISSUE THREAD

**Issue by kcaran** [teodesian/playwright-perl#62]
Hi. I'm finally converting my Selenium tests to Playwright. Thank you!

I tried to run `reap_playwright_servers` but it gives an error:

```
Too few arguments for subroutine 'Playwright::Util::request' (got 4; expected at least 5) at /usr/local/bin/reap_playwright_servers line 29.
 at /usr/local/bin/reap_playwright_servers line 29.
```

It looks like https://github.com/teodesian/playwright-perl/issues/51 added a $host argument. If I add 'localhost' to the  Playwright::Util::request() call in reap_playwright_servers it works fine.

I would be happy to create a pull request but wanted your thoughts.

**Comment by teodesian** [comment]
Please do, I'm happy for any and all pull requests.  I'm busy with a move right now, so you can probably put it together faster than I can.
