### ISSUE TITLE
generate_api_json.sh - sed in-place syntax differences between BSD and GNU

### ISSUE THREAD

**Issue by kcaran** [teodesian/playwright-perl#69]
It looks like GNU (Linux) and BSD(MacOS) have incompatible ways of defining in-place file replacement for sed. This is the best explanation I could find:

https://stackoverflow.com/questions/34281077/how-to-make-sed-i-work-in-both-mac-and-ubuntu

I came up with two possible solutions:

1) Use perl instead of sed
```
perl -i -pe 'BEGIN{ $api = `cat api.json`; chomp $api } s/%REPLACEME%/\n$api/' bin/playwright_server
```

2) Backup bin/playwright_server to bin/playwright_server.bak and delete the file afterwards. This works on Linux and MacOS both:

```
sed -i.bak -e '/%REPLACEME%/r api.json' -e 's/%REPLACEME%//g' bin/playwright_server
rm bin/playwright_server.bak
```

Would one of these solutions be OK? I could also add some updates to quiet the program under normal execution (like using `mkdir -p` and `git pull -q`.

**Comment by teodesian** [comment]
Yes, either would be fine.  The latter is probably an easier implementation -- send me a PR and I will merge it immediately.
